cinst ConEmu
cinst notepadplusplus
cinst Firefox
cinst vim
cinst bitdefenderavfree
cinst dropbox
cinst ccleaner
cinst gimp
cinst malwarebytes
cinst 7zip
cinst fiddler4
cinst GoogleChrome
cinst virtualbox
cinst PDFCreator
cinst sumatrapdf.install
cinst sublimetext2
cinst vlc
cinst winmerge
cinst pencil
cinst SourceCodePro
cinst webpi
cinst launchy
cinst git
cinst lockhunter
cinst nodejs.install
cinst cdburnerxp
cinst windirstat
cinst linqpad4
cinst recuva
cinst HxD
cinst greenshot 
